 [build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "PyGeoX"
version = "0.2.0"
description = "Declarative geometry package for Python"
readme = "README.md"
requires-python = ">=3.7"
authors = [
    {name = "Rafael Cabral"}
]
license = {text = "MIT"}
classifiers = [
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.7",
    "Programming Language :: Python :: 3.8",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]
dependencies = [
    "sympy",
    "matplotlib",
    "numba",
    "numpy",
    "scipy==1.13.1",
    "typeguard",
    "Pillow",
    "tqdm"
]

[tool.setuptools.packages.find]
where = ["pygeox"]

[project.urls]
Homepage = "https://gitlab-sg-green.rnd.huawei.com/r00922822/pygeox"